name: "git sync branches"
description: "GitHub Action to copy and push commits from one branch to another."
author: "levibostian"
inputs: # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
  ahead:
    description: "Branch that has commits in it that are not in the *behind* branch that you want to copy over."
    required: true
  behind:
    description: "Branch that you want to copy commits *into*. This branch is missing commits that are in *ahead* branch"
    required: true
  githubToken:
    description: "GitHub personal access token for a GitHub account that has push access to the repository."
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout all branches and commits history 
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Sync branches 
      run: ${{ github.action_path }}/action.sh ${{ inputs.ahead }} ${{ inputs.behind }}
      shell: bash 

branding:
  icon: 'refresh-cw'  
  color: 'yellow'