name: Sync release branches with develop

on: [push]

jobs:
  sync-branches:
    name: Sync branches 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync develop and alpha
        uses: ./ 
        with:
          behind: develop
          ahead: alpha 
          githubToken: ${{ secrets.BOT_PUSH_TOKEN }}
      - name: Sync develop and beta
        uses: ./ 
        with:
          behind: develop
          ahead: beta 
          githubToken: ${{ secrets.BOT_PUSH_TOKEN }}
      - name: Sync develop and main
        uses: ./ 
        with:
          behind: develop
          ahead: main 
          githubToken: ${{ secrets.BOT_PUSH_TOKEN }}